### ISSUE TITLE
移植到android的错误

### ISSUE THREAD

**Issue by Liu-Eleven** [chengjianxi/Weather#1]
E linker  : library "/system/lib/libcrypto.so" ("/system/lib/libcrypto.so") needed or dlopened by "/data/app/org.kaboo.weather-2/lib/arm/libQt5Core.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/org.kaboo.weather-2/lib/arm:/data/app/org.kaboo.weather-2/base.apk!/lib/armeabi-v7a", permitted_paths="/data:/mnt/expand:/data/data/org.kaboo.weather"]
W Weather : qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed
D Weather : qml: 调用接口失败，0

**Comment by chengjianxi** [comment]
抱歉Github上的版本由于本人近期太忙没有及时更新，最新版的请在码云上下载。
https://gitee.com/chengjianxi/Weather

这是由于安装到安卓时缺少libcrypto.so和libssl.so引起的问题。

**Comment by Liu-Eleven** [comment]
很高兴收到您的回复，看了您的这个天气预报app，从中学到了qt开发android第一个app!希望以后有机会多多和大佬交流。




------------------ 原始邮件 ------------------
发件人: "JX Cheng"<notifications@github.com>;
发送时间: 2019年5月10日(星期五) 下午2:18
收件人: "chengjianxi/Weather"<Weather@noreply.github.com>;
抄送: "刘一儿"<1024847801@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chengjianxi/Weather] 移植到android的错误 (#1)




抱歉Github上的版本由于本人近期太忙没有及时更新，最新版的请在码云上下载。
 https://gitee.com/chengjianxi/Weather
 
这是由于安装到安卓时缺少libcrypto.so和libssl.so引起的问题。
